USE master;
GO

declare @ExecSQL nvarchar(max)
set @ExecSQL = REPLACE('
-- the following is eliminated with a running version
IF DB_ID (N''@DBName'') IS NOT NULL
BEGIN
--   RAISERROR(N''@DBName Database Already Exists!'', 16, 127) WITH NOWAIT
   alter database [@DBName] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
   DROP DATABASE [@DBName]
END
   CREATE DATABASE [@DBName]
   COLLATE SQL_Latin1_General_CP1_CI_AS
   WITH TRUSTWORTHY ON, DB_CHAINING ON;

   PRINT ''***** Created @DBName Database *****''
   --Verifying collation and option settings.
   SELECT name, collation_name, is_trustworthy_on, is_db_chaining_on
   FROM sys.databases
   WHERE name = N''@DBName''

   IF (1 = FULLTEXTSERVICEPROPERTY(''IsFullTextInstalled''))
   BEGIN
   	EXEC [@DBName].[dbo].[sp_fulltext_database] @action = ''enable''
   END

    ALTER DATABASE [@DBName] SET ANSI_NULL_DEFAULT OFF 
    ALTER DATABASE [@DBName] SET ANSI_NULLS OFF 
    ALTER DATABASE [@DBName] SET ANSI_PADDING OFF 
    ALTER DATABASE [@DBName] SET ANSI_WARNINGS OFF 
    ALTER DATABASE [@DBName] SET ARITHABORT OFF 
    ALTER DATABASE [@DBName] SET AUTO_CLOSE OFF 
    ALTER DATABASE [@DBName] SET AUTO_CREATE_STATISTICS ON 
    ALTER DATABASE [@DBName] SET AUTO_SHRINK OFF 
    ALTER DATABASE [@DBName] SET AUTO_UPDATE_STATISTICS ON 
    ALTER DATABASE [@DBName] SET CURSOR_CLOSE_ON_COMMIT OFF 
    ALTER DATABASE [@DBName] SET CURSOR_DEFAULT  GLOBAL 
    ALTER DATABASE [@DBName] SET CONCAT_NULL_YIELDS_NULL OFF 
    ALTER DATABASE [@DBName] SET NUMERIC_ROUNDABORT OFF 
    ALTER DATABASE [@DBName] SET QUOTED_IDENTIFIER OFF 
    ALTER DATABASE [@DBName] SET RECURSIVE_TRIGGERS OFF 
    ALTER DATABASE [@DBName] SET  DISABLE_BROKER 
    ALTER DATABASE [@DBName] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
    ALTER DATABASE [@DBName] SET DATE_CORRELATION_OPTIMIZATION OFF 
    ALTER DATABASE [@DBName] SET TRUSTWORTHY OFF 
    ALTER DATABASE [@DBName] SET ALLOW_SNAPSHOT_ISOLATION OFF 
    ALTER DATABASE [@DBName] SET PARAMETERIZATION SIMPLE 
    ALTER DATABASE [@DBName] SET READ_COMMITTED_SNAPSHOT OFF 
    ALTER DATABASE [@DBName] SET HONOR_BROKER_PRIORITY OFF 
    ALTER DATABASE [@DBName] SET  READ_WRITE 
    ALTER DATABASE [@DBName] SET RECOVERY FULL 
    ALTER DATABASE [@DBName] SET  MULTI_USER 
    ALTER DATABASE [@DBName] SET PAGE_VERIFY CHECKSUM  
    ALTER DATABASE [@DBName] SET DB_CHAINING OFF 

IF DB_ID (N''@DBName'') IS NOT NULL
BEGIN
   EXEC [@DBName].dbo.sp_changedbowner ''sa''
END
', '@DBName', $(DBName))
Exec(@ExecSQL)
GO