//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Query_Service.ExtensionForTests.DataProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestHeader", Namespace="http://schemas.datacontract.org/2004/07/Query_Service.ExtensionForTests.DataProxy" +
        "")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Query_Service.ExtensionForTests.DataProxy.UpdateSoftDeleteRequestDC))]
    public partial class RequestHeader : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IncallerField;
        
        private string IncallerVersionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Incaller
        {
            get
            {
                return this.IncallerField;
            }
            set
            {
                this.IncallerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IncallerVersion
        {
            get
            {
                return this.IncallerVersionField;
            }
            set
            {
                this.IncallerVersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateSoftDeleteRequestDC", Namespace="http://schemas.datacontract.org/2004/07/Query_Service.ExtensionForTests.DataProxy" +
        "")]
    public partial class UpdateSoftDeleteRequestDC : Query_Service.ExtensionForTests.DataProxy.RequestHeader
    {
        
        private string IdField;
        
        private string TableNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableName
        {
            get
            {
                return this.TableNameField;
            }
            set
            {
                this.TableNameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ClearLockRequestDC", Namespace = "http://schemas.datacontract.org/2004/07/Query_Service.ExtensionForTests.DataProxy" +
        "")]
    public partial class ClearLockRequestDC : Query_Service.ExtensionForTests.DataProxy.RequestHeader
    {
        private string name;
        private string version;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get { return this.name; }
            set { this.name = value; }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version
        {
            get { return this.version; }
            set { this.version = value; }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusReplyDC", Namespace="http://schemas.datacontract.org/2004/07/Query_Service.ExtensionForTests.DataProxy" +
        "")]
    public partial class StatusReplyDC : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorMessageField;
        
        private int ErrorcodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Errorcode
        {
            get
            {
                return this.ErrorcodeField;
            }
            set
            {
                this.ErrorcodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReplyHeader", Namespace="http://schemas.datacontract.org/2004/07/Query_Service.ExtensionForTests.DataProxy" +
        "")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Query_Service.ExtensionForTests.DataProxy.ErrorLogGetReplyDC))]
    public partial class ReplyHeader : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Query_Service.ExtensionForTests.DataProxy.StatusReplyDC StatusReplyField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Query_Service.ExtensionForTests.DataProxy.StatusReplyDC StatusReply
        {
            get
            {
                return this.StatusReplyField;
            }
            set
            {
                this.StatusReplyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorLogGetReplyDC", Namespace="http://schemas.datacontract.org/2004/07/Query_Service.ExtensionForTests.DataProxy" +
        "")]
    public partial class ErrorLogGetReplyDC : Query_Service.ExtensionForTests.DataProxy.ReplyHeader
    {
        
        private string AppDomainNameField;
        
        private string FormattedMessageField;
        
        private string MachineNameField;
        
        private string MessageField;
        
        private int PriorityField;
        
        private string ProcessIdField;
        
        private string ProcessNameField;
        
        private string SeverityField;
        
        private string ThreadNameField;
        
        private System.DateTime TimestampField;
        
        private string TitleField;
        
        private string Win32ThreadIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppDomainName
        {
            get
            {
                return this.AppDomainNameField;
            }
            set
            {
                this.AppDomainNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormattedMessage
        {
            get
            {
                return this.FormattedMessageField;
            }
            set
            {
                this.FormattedMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MachineName
        {
            get
            {
                return this.MachineNameField;
            }
            set
            {
                this.MachineNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessId
        {
            get
            {
                return this.ProcessIdField;
            }
            set
            {
                this.ProcessIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessName
        {
            get
            {
                return this.ProcessNameField;
            }
            set
            {
                this.ProcessNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Severity
        {
            get
            {
                return this.SeverityField;
            }
            set
            {
                this.SeverityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThreadName
        {
            get
            {
                return this.ThreadNameField;
            }
            set
            {
                this.ThreadNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Win32ThreadId
        {
            get
            {
                return this.Win32ThreadIdField;
            }
            set
            {
                this.Win32ThreadIdField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IQueryServiceExtension")]
public interface IQueryServiceExtension
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryServiceExtension/UpdateSoftDelete", ReplyAction="http://tempuri.org/IQueryServiceExtension/UpdateSoftDeleteResponse")]
    Query_Service.ExtensionForTests.DataProxy.StatusReplyDC UpdateSoftDelete(Query_Service.ExtensionForTests.DataProxy.UpdateSoftDeleteRequestDC request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryServiceExtension/DeleteFromId", ReplyAction="http://tempuri.org/IQueryServiceExtension/DeleteFromIdResponse")]
    Query_Service.ExtensionForTests.DataProxy.StatusReplyDC DeleteFromId(int id, string table, string database);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryServiceExtension/ErrorLogGet", ReplyAction="http://tempuri.org/IQueryServiceExtension/ErrorLogGetResponse")]
    Query_Service.ExtensionForTests.DataProxy.ErrorLogGetReplyDC ErrorLogGet(int errorLogId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IQueryServiceExtension/ClearLock", ReplyAction = "http://tempuri.org/IQueryServiceExtension/ClearLockResponse")]
    Query_Service.ExtensionForTests.DataProxy.StatusReplyDC ClearLock(Query_Service.ExtensionForTests.DataProxy.ClearLockRequestDC request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IQueryServiceExtensionChannel : IQueryServiceExtension, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class QueryServiceExtensionClient : System.ServiceModel.ClientBase<IQueryServiceExtension>, IQueryServiceExtension
{
    
    public QueryServiceExtensionClient()
    {
    }
    
    public QueryServiceExtensionClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public QueryServiceExtensionClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public QueryServiceExtensionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public QueryServiceExtensionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Query_Service.ExtensionForTests.DataProxy.StatusReplyDC UpdateSoftDelete(Query_Service.ExtensionForTests.DataProxy.UpdateSoftDeleteRequestDC request)
    {
        return base.Channel.UpdateSoftDelete(request);
    }
    
    public Query_Service.ExtensionForTests.DataProxy.StatusReplyDC DeleteFromId(int id, string table, string database)
    {
        return base.Channel.DeleteFromId(id, table, database);
    }

    public Query_Service.ExtensionForTests.DataProxy.StatusReplyDC ClearLock(Query_Service.ExtensionForTests.DataProxy.ClearLockRequestDC request)
    {
        return base.Channel.ClearLock(request);
    }
    
    public Query_Service.ExtensionForTests.DataProxy.ErrorLogGetReplyDC ErrorLogGet(int errorLogId)
    {
        return base.Channel.ErrorLogGet(errorLogId);
    }
}
