SET ANSI_DEFAULTS ON
SET CURSOR_CLOSE_ON_COMMIT OFF
SET IMPLICIT_TRANSACTIONS OFF
SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET NUMERIC_ROUNDABORT OFF
SET QUOTED_IDENTIFIER ON
 
SET DATEFORMAT ymd
SET LOCK_TIMEOUT -1
SET NOCOUNT ON
SET ROWCOUNT 0
SET TEXTSIZE 0
GO
 
 
PRINT '    Adding CONSTRAINTS To [AuthorizationGroup]'

ALTER TABLE [dbo].[AuthorizationGroup]  WITH CHECK ADD  CONSTRAINT [FK_AuthorizationGroup_Role] FOREIGN KEY([RoleId])
REFERENCES [dbo].[Role] ([Id])
GO

ALTER TABLE [dbo].[AuthorizationGroup] CHECK CONSTRAINT [FK_AuthorizationGroup_Role]
GO

