SET ANSI_DEFAULTS ON
SET CURSOR_CLOSE_ON_COMMIT OFF
SET IMPLICIT_TRANSACTIONS OFF
SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET NUMERIC_ROUNDABORT OFF
SET QUOTED_IDENTIFIER ON
 
SET DATEFORMAT ymd
SET LOCK_TIMEOUT -1
SET NOCOUNT ON
SET ROWCOUNT 0
SET TEXTSIZE 0
GO

PRINT '    Adding CONSTRAINTS To [RoleEnvPermission]'

ALTER TABLE [dbo].[RoleEnvPermission]  WITH CHECK ADD  CONSTRAINT [FK_Environment_RoleEnvPermission] FOREIGN KEY([EnvId])
REFERENCES [dbo].[Environment] ([Id])
GO

ALTER TABLE [dbo].[RoleEnvPermission] CHECK CONSTRAINT [FK_Environment_RoleEnvPermission]
GO

ALTER TABLE [dbo].[RoleEnvPermission]  WITH CHECK ADD  CONSTRAINT [FK_Role_RoleEnvPermission] FOREIGN KEY([RoleId])
REFERENCES [dbo].[Role] ([Id])
GO

ALTER TABLE [dbo].[RoleEnvPermission] CHECK CONSTRAINT [FK_Role_RoleEnvPermission]
GO

CREATE UNIQUE NONCLUSTERED INDEX [UQ_RoleEnvPermission_RoleId_EnvId] ON [dbo].[RoleEnvPermission]
(
	[RoleId] ASC,
	[EnvId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

